name: absen_smkn1_punggelan
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  get_it: ^8.0.3
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  http: ^1.3.0
  image_picker: ^1.0.7
  image_cropper: ^9.0.0
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  device_info_plus: ^11.3.0
  flutter_face_api: ^6.2.2
  flutter_face_core_basic: ^6.2.1
  flutter_osm_plugin: ^1.0.5
  geolocator: ^13.0.2
  freezed_annotation: ^2.4.1
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.12.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.9
  freezed: ^2.4.7
  analyzer: ^7.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_sekolah.png
    - assets/images/google_icon.png
    - assets/icon/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"